import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
};

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter",
	display: "swap"
});

export default function RootLayout({
	children
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.variable} antialiased bg-background-base `}>{children}</body>
		</html>
	);
}
